In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv('C:/Users/69009/Desktop/last/441/problem/CALI.csv')
print(dataset)

       MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
5      4.0368      52.0  4.761658   1.103627       413.0  2.139896     37.85   
6      3.6591      52.0  4.931907   0.951362      1094.0  2.128405     37.84   
7      3.1200      52.0  4.797527   1.061824      1157.0  1.788253     37.84   
8      2.0804      42.0  4.294118   1.117647      1206.0  2.026891     37.84   
9      3.6912      52.0  4.970588   0.990196      1551.0  2.172269     37.84   
10     3.2031      52.0  5.477612   1.079602       910.0  2.263682     37.85   
11     3.2705      52.0  4.772480   1.02

In [3]:
feature_names={"MedInc","HouseAge","AveRooms","AveBedrms","Population","AveOccup","Latitude","Longitude"}
df_x = pd.DataFrame(dataset, columns = feature_names)
df_y = pd.DataFrame(dataset, columns = {"HOUSING PRICE"})
df_x

HouseAge  Latitude  AveOccup  Longitude  Population  MedInc  AveRooms  \
0          41.0     37.88  2.555556    -122.23       322.0  8.3252  6.984127   
1          21.0     37.86  2.109842    -122.22      2401.0  8.3014  6.238137   
2          52.0     37.85  2.802260    -122.24       496.0  7.2574  8.288136   
3          52.0     37.85  2.547945    -122.25       558.0  5.6431  5.817352   
4          52.0     37.85  2.181467    -122.25       565.0  3.8462  6.281853   
5          52.0     37.85  2.139896    -122.25       413.0  4.0368  4.761658   
6          52.0     37.84  2.128405    -122.25      1094.0  3.6591  4.931907   
7          52.0     37.84  1.788253    -122.25      1157.0  3.1200  4.797527   
8          42.0     37.84  2.026891    -122.26      1206.0  2.0804  4.294118   
9          52.0     37.84  2.172269    -122.25      1551.0  3.6912  4.970588   
10         52.0     37.85  2.263682    -122.26       910.0  3.2031  5.477612   
11         52.0     37.85  2.049046    -122.26      1504.0  3.2705  4.772480   
12         52.0     37.85  2.346154    -122.26      1098.0  3.0750  5.322650   
13         52.0     37.84  1.982759    -122.26       345.0  2.6736  4.000000   
14         52.0     37.85  1.954839    -122.26      1212.0  1.9167  4.262903   
15         50.0     37.85  2.640152    -122.26       697.0  2.1250  4.242424   
16         52.0     37.85  2.395770    -122.27       793.0  2.7750  5.939577   
17         52.0     37.85  2.138614    -122.27       648.0  2.1202  4.052805   
18         50.0     37.84  2.362768    -122.26       990.0  1.9911  5.343675   
19         52.0     37.84  2.509091    -122.27       690.0  2.6033  5.465455   
20         40.0     37.85  2.463855    -122.27       409.0  1.3578  4.524096   
21         42.0     37.85  2.538251    -122.27       929.0  1.7135  4.478142   
22         52.0     37.84  2.123431    -122.27      1015.0  1.7250  5.096234   
23         52.0     37.84  2.624615    -122.27       853.0  2.1806  5.193846   
24         52.0     37.84  2.383886    -122.27      1006.0  2.6000  5.270142   
25         41.0     37.85  2.663866    -122.28       317.0  2.4038  4.495798   
26         49.0     37.85  2.539749    -122.28       607.0  2.4597  4.728033   
27         52.0     37.85  2.775819    -122.28      1102.0  1.8080  4.780856   
28         50.0     37.84  2.391121    -122.28      1131.0  1.6424  4.401691   
29         52.0     37.84  2.548387    -122.28       395.0  1.6875  4.703226   
...         ...       ...       ...        ...         ...     ...       ...   
20610      28.0     39.10  2.722096    -121.56      1195.0  1.3631  4.851936   
20611      27.0     39.10  2.843521    -121.55      1163.0  1.2857  4.359413   
20612      26.0     39.08  2.850187    -121.56       761.0  1.4934  5.157303   
20613      31.0     39.09  3.039062    -121.55      1167.0  1.4958  4.500000   
20614      26.0     39.08  3.069620    -121.54      1455.0  2.4695  4.801688   
20615      23.0     39.08  3.675127    -121.54       724.0  2.3598  5.461929   
20616      15.0     39.08  3.085333    -121.53      1157.0  2.0469  4.826667   
20617      20.0     39.06  2.701754    -121.53       308.0  3.3021  4.921053   
20618      25.0     39.06  3.212389    -121.55       726.0  2.2500  5.893805   
20619      22.0     39.01  3.456081    -121.56      1023.0  2.7303  6.388514   
20620      40.0     39.05  3.145833    -121.48       151.0  4.5625  4.125000   
20621      37.0     39.01  3.082803    -121.47       484.0  2.3661  7.923567   
20622      20.0     39.00  2.910828    -121.44       457.0  2.4167  4.808917   
20623      32.0     39.03  2.634361    -121.37       598.0  2.8235  5.101322   
20624      16.0     39.04  2.512027    -121.41       731.0  3.0739  5.835052   
20625      37.0     39.12  2.071429    -121.52        29.0  4.1250  7.285714   
20626      36.0     39.18  2.947368    -121.43       504.0  2.1667  6.573099   
20627       5.0     39.13  2.864407    -121.32       169.0  3.0000  6.067797   
20628  

In [4]:
for column in df_x.columns:
    df_x[column] = (df_x[column] - df_x[column].min()) / (df_x[column].max() - df_x[column].min())
df_x

HouseAge  Latitude  AveOccup  Longitude  Population    MedInc  \
0      0.784314  0.567481  0.001499   0.211155    0.008941  0.539668   
1      0.392157  0.565356  0.001141   0.212151    0.067210  0.538027   
2      1.000000  0.564293  0.001698   0.210159    0.013818  0.466028   
3      1.000000  0.564293  0.001493   0.209163    0.015555  0.354699   
4      1.000000  0.564293  0.001198   0.209163    0.015752  0.230776   
5      1.000000  0.564293  0.001165   0.209163    0.011491  0.243921   
6      1.000000  0.563231  0.001156   0.209163    0.030578  0.217873   
7      1.000000  0.563231  0.000882   0.209163    0.032344  0.180694   
8      0.803922  0.563231  0.001074   0.208167    0.033717  0.108998   
9      1.000000  0.563231  0.001191   0.209163    0.043387  0.220087   
10     1.000000  0.564293  0.001265   0.208167    0.025421  0.186425   
11     1.000000  0.564293  0.001092   0.208167    0.042070  0.191073   
12     1.000000  0.564293  0.001331   0.208167    0.030690  0.177591   
13     1.000000  0.563231  0.001038   0.208167    0.009585  0.149908   
14     1.000000  0.564293  0.001016   0.208167    0.033885  0.097709   
15     0.960784  0.564293  0.001568   0.208167    0.019451  0.112074   
16     1.000000  0.564293  0.001371   0.207171    0.022142  0.156901   
17     1.000000  0.564293  0.001164   0.207171    0.018078  0.111743   
18     0.960784  0.563231  0.001344   0.208167    0.027663  0.102840   
19     1.000000  0.563231  0.001462   0.207171    0.019255  0.145060   
20     0.764706  0.564293  0.001426   0.207171    0.011379  0.059165   
21     0.803922  0.564293  0.001486   0.207171    0.025954  0.083695   
22     1.000000  0.563231  0.001152   0.207171    0.028364  0.084488   
23     1.000000  0.563231  0.001555   0.207171    0.023824  0.115909   
24     1.000000  0.563231  0.001361   0.207171    0.028112  0.144832   
25     0.784314  0.564293  0.001587   0.206175    0.008801  0.131302   
26     0.941176  0.564293  0.001487   0.206175    0.016929  0.135157   
27     1.000000  0.564293  0.001677   0.206175    0.030802  0.090213   
28     0.960784  0.563231  0.001367   0.206175    0.031615  0.078792   
29     1.000000  0.563231  0.001494   0.206175    0.010987  0.081902   
...         ...       ...       ...        ...         ...       ...   
20610  0.529412  0.697131  0.001633   0.277888    0.033409  0.059530   
20611  0.509804  0.697131  0.001731   0.278884    0.032512  0.054192   
20612  0.490196  0.695005  0.001737   0.277888    0.021245  0.068516   
20613  0.588235  0.696068  0.001889   0.278884    0.032624  0.068682   
20614  0.490196  0.695005  0.001913   0.279880    0.040696  0.135833   
20615  0.431373  0.695005  0.002400   0.279880    0.020208  0.128267   
20616  0.274510  0.695005  0.001926   0.280876    0.032344  0.106688   
20617  0.372549  0.692880  0.001617   0.280876    0.008548  0.193253   
20618  0.470588  0.692880  0.002028   0.278884    0.020264  0.120695   
20619  0.411765  0.687566  0.002224   0.277888    0.028588  0.153819   
20620  0.764706  0.691817  0.001974   0.285857    0.004148  0.280175   
20621  0.705882  0.687566  0.001924   0.286853    0.013481  0.128702   
20622  0.372549  0.686504  0.001785   0.289841    0.012725  0.132191   
20623  0.607843  0.689692  0.001563   0.296813    0.016676  0.160246   
20624  0.294118  0.690755  0.001464   0.292829    0.020404  0.177515   
20625  0.705882  0.699256  0.001110   0.281873    0.000729  0.250003   
20626  0.686275  0.705632  0.001815   0.290837    0.014042  0.114950   
20627  0.078431  0.700319  0.001748   0.301793    0.004653  0.172418   
20628  0.352941  0.697131  0.001543   0.285857    0.028448  0.144501   
20629  0.529412  0.699256  0.002502   0.294821    0.193643  0.109957   
20630  0.196078  0.717322  0.001716   0.301793    0.035147  0.211542   
20631  0.274510  0.721573  0.001678   0.293825    0.033549  0.208135   
20632  0.274510  0.714134  0.001631   0.288845    0.029261  0.181039   
20633  0.509804  0.706695  0.001722   0.280876 

In [5]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size = 0.2, random_state = 4)

In [6]:
model = linear_model.LinearRegression()
model.fit(x_train,y_train)
results = model.predict(x_test)
print(results)

[[2.06302041]
 [2.50552547]
 [1.61461714]
 ...
 [1.88260187]
 [2.39154106]
 [0.30191159]]


In [7]:
model.coef_

array([[  0.47803918,  -3.99331079,  -4.33923437,  -4.40246164,
         -0.19455488,   6.33030675, -15.47310652,  21.11153934]])

In [8]:
from sklearn.metrics import mean_squared_error, r2_score
model_score = model.score(x_train,y_train)
print('R2 sq: ', model_score)
# The mean squared error
print("Mean squared error: %.2f"% mean_squared_error(y_test, results))
# Explained variance score: 1 is perfect prediction
print('Test Variance score: %.2f' % r2_score(y_test, results))

R2 sq:  0.6083953032289722
Mean squared error: 0.53
Test Variance score: 0.60


In [9]:
print(np.c_[y_test.values, results][0:5,:])

[[1.752      2.06302041]
 [3.147      2.50552547]
 [0.9        1.61461714]
 [1.231      1.39379827]
 [3.509      2.59927355]]
